### ISSUE TITLE
TypeError: Cannot call method 'SHA256' of undefined

### ISSUE THREAD

**Issue by dr-dimitru** [VeliovGroup/ostrio-Neo4jreactivity#10]
Somewhy Meteor doesn't automatically bind some [Utility Packages](https://www.meteor.com/utilities), if they are even requested in [package.js](https://github.com/VeliovGroup/ostrio-Neo4jreactivity/blob/master/package.js#L15)

To solve this issue simply run (inside meteor's project folder):
```bash
meteor add sha
```

**Comment by JackAdams** [comment]
If you want `SHA256` available outside of your package, in other parts of the app, put this line in your `package.js` file:
    `api.imply('sha');`
