### ISSUE TITLE
Aggregation operators support

### ISSUE THREAD

**Issue by vraptor75011** [VeliovGroup/ostrio-Neo4jreactivity#14]
Hi,

This doesn't seem to work 
```coffeescript
Meteor.neo4j.query("MATCH (a:Societe), (b:Societe {_id:{Id}}) WHERE (b)-[:OWNS]->(a) RETURN count(a)", Id: @_id).get()
```

It returns an array name count(a) with nothing inside. Same query with RETURN a is fine.

Any ideas ?

**Comment by dr-dimitru** [comment]
@vraptor75011  this issue will be fixed in next release - very soon

**Comment by vraptor75011** [comment]
Tks !

**Comment by dr-dimitru** [comment]
@vraptor75011 fixed in: https://github.com/VeliovGroup/ostrio-Neo4jreactivity/commit/3ca874c490bd51c6f39010727a8190a50e09969e
