### ISSUE TITLE
Differences between Meteor.neo4j.call and Meteor.neo4j.query

### ISSUE THREAD

**Issue by vraptor75011** [VeliovGroup/ostrio-Neo4jreactivity#17]
According to your comments both should return reactive objet of same type.

Meteor.neo4j.query works as expected with a get() to retrieve the object

Meteor.neo4j.call doesn't return anything. Is this normal ?

I wanted to use the call method in order not to expose the query in the js client file. I intend to run the same query wether with call or query

**Comment by dr-dimitru** [comment]
@vraptor75011  I think issue might be in data parser, could you please provide part of data and exact query you are running on it?

**Comment by dr-dimitru** [comment]
@vraptor75011 could you please provide part of data and exact query you are running on it?

**Comment by vraptor75011** [comment]
Sorry for the delay,

Template helper

```coffeescript
Template.listSocietes.helpers
    societes: ->
      var1 = Meteor.neo4j.call("racineSociete")
      var2 = Meteor.neo4j.query("MATCH (a:Societe) WHERE NOT ()-[:OWNS]->(a) RETURN a ORDER BY a.name ASC").get()
      console.log var1, var2
      return var1
```

Method

```coffeescript
Meteor.neo4j.methods
  racineSociete: ->
    "MATCH (a:Societe) WHERE NOT ()-[:OWNS]->(a) RETURN a ORDER BY a.name ASC"
```
in template file, var1 is permanently undefined where var2 is OK.

With var1, if I use a callback, result is OK in the callback function but I can t use it as a return value of my temple helper.

**Comment by vraptor75011** [comment]
I finally managed to use meteor.neo4j.call as a return value of a template helper.
I created a reactive var with template.created and a template.instance.rvar.get as the return value of template helper.

**Comment by dr-dimitru** [comment]
@vraptor75011 Because Meteor.neo4j.call return data `into callback(err, data)`, from the docs:
###### In Server Methods
```coffeescript
#CoffeeScript
Meteor.neo4j.methods 
    getUsersFriends: () ->
        return  'MATCH (a:User {_id: {userId}})-[relation:friends]->(b:User) ' +
                'OPTIONAL MATCH (b:User)-[subrelation:friends]->() ' +
                'RETURN relation, subrelation, b._id AS b_id, b'
```

###### In Helper
```coffeescript
#CoffeeScript
Template.friendsNamesList.helpers
    userFriends: () ->

        Meteor.neo4j.call 'getUsersFriends', {userId: '12345'}, (error, data) ->
            if error
                 #handle error here
                 throw new Meteor.error '500', 'Something goes wrong here', error.toString()
            else
                Session.set 'currenUserFriends', data

        return Session.get 'currentUserFriens'
```

**Comment by dr-dimitru** [comment]
@vraptor75011 any news around this issue on your end?

**Comment by vraptor75011** [comment]
Yes.
As I wrote in my previous post, I didn't use a session variable because the return result is different for each instance of the template and I used Meteor.neo4j.call in order not to expose the query in the js served to the client.

In Helper
```coffeescript
Template.listSocietes.helpers
    societes: ->
      return Template.instance().societes.get()

    selectedSocieteName: ->
      Session.get "selectedSocieteName"

    selectedSociete: ->
      Session.get "selectedSociete"

Template.listSocietes.created = ->
  this.societes = new ReactiveVar(null)
  self = this
  if this.data?.idSoc?
    Meteor.neo4j.call "societesOwned", {Id: @data.idSoc}, (error, data) ->
      console.log "DATAFILLE", data, self
      self.societes.set data
  else
    Meteor.neo4j.call "racineSociete", {}, (error, data) ->
      console.log "DATA", data, self
      self.societes.set data
```
