### ISSUE TITLE
Neo4j publish

### ISSUE THREAD

**Issue by alexfrieden** [VeliovGroup/ostrio-Neo4jreactivity#21]
Currently doing this:
```
Meteor.publish('bits', function() {
  return Bits.get();
});
```

But getting:
```
Exception from sub 63YhhFDEbd3YC78G6 Error: Publish function can only return a Cursor or an array of Cursors
```
Is there a neo4j workaround for this?

**Comment by dr-dimitru** [comment]
No need to do a publish for Neo4j
Just simply query DB for data directly from Client or Server, or via methods
