### ISSUE TITLE
Exception in callback of async function: Error: Neo4jCacheCollection.upsert

### ISSUE THREAD

**Issue by snowcxt** [VeliovGroup/ostrio-Neo4jreactivity#22]
I tried to run the Meteor-Leaderboard-Neo4j (https://github.com/VeliovGroup/Meteor-Leaderboard-Neo4j) example today. However I got an exception: "Exception in callback of async function: Error: Neo4jCacheCollection.upsert:

![unnamed](https://cloud.githubusercontent.com/assets/1463415/6644374/7fbb00d6-c970-11e4-9a01-b768ee70eb13.png)

BTW, I'm using windows and install Preview of Meteor on Windows 0.2.8 (https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows).

**Comment by dr-dimitru** [comment]
Hi @snowcxt , are you sure there is no changes in Meteor-Leaderboard-Neo4j made by you?
Also make sure Neo4j is installed, running and available on: localhost:7474

**Comment by snowcxt** [comment]
Hi folks,

I changed the release file (under Meteor-Leaderboard-Neo4j-master\.meteor)
from *METEOR@1.0.3.2 <METEOR@1.0.3.2>* to *WINDOWS-PREVIEW@0.2.8* otherwise
I can't run the example on my windows box. Is that the reason?

Thomas

On Fri, Mar 13, 2015 at 11:24 AM, dr.dimitru <notifications@github.com>
wrote:

> Hi @snowcxt <https://github.com/snowcxt> , are you sure there is no
> changes in Meteor-Leaderboard-Neo4j made by you?
> Also make sure Neo4j is installed, running and available on: localhost:7474
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/VeliovGroup/ostrio-Neo4jreactivity/issues/22#issuecomment-79217995>
> .
>



-- 
Thanks,
Thomas

**Comment by snowcxt** [comment]
I changed the release file (under Meteor-Leaderboard-Neo4j-master\.meteor) from METEOR@1.0.3.2 to WINDOWS-PREVIEW@0.2.8 otherwise I can't run the example on my windows box. Is that the reason?

**Comment by dr-dimitru** [comment]
@snowcxt might be, could you confirm what everything is working now? If so, I'll add this to docs

**Comment by snowcxt** [comment]
I have to keep using WINDOWS-PREVIEW@0.2.8. If I changed back to "METEOR@1.0.3.2", I'll get:
![image](https://cloud.githubusercontent.com/assets/1463415/6645004/d3e3e830-c975-11e4-8b39-706caa87048c.png)

**Comment by snowcxt** [comment]
I have to keep using WINDOWS-PREVIEW@0.2.8. If I change back to "
METEOR@1.0.3.2", I'll get:



Thanks,
Thomas

**Comment by dr-dimitru** [comment]
@snowcxt glad you solve it

**Comment by snowcxt** [comment]
I have not resolved it. I still get same error.

**Comment by snowcxt** [comment]
Let me explain the issue again. I'm using windows and Preview of Meteor on
Windows 0.2.8. When I download the example and run, I got this error:
[image: image]

So I changed the release file (under
Meteor-Leaderboard-Neo4j-master\.meteor)
from "METEOR@1.0.3.2" to "WINDOWS-PREVIEW@0.2.8"

Then I can run the example, but I got this error then:


I still don't know to fix this issue.

**Comment by snowcxt** [comment]
Let me explain the issue again. I'm using windows and Preview of Meteor on Windows 0.2.8. When I download the example and run, I got this error:
![image](https://cloud.githubusercontent.com/assets/1463415/6647700/7063c8fc-c98e-11e4-8dfd-92d5d3950e60.png)

So I changed the release file (under Meteor-Leaderboard-Neo4j-master\.meteor) from "METEOR@1.0.3.2" to "WINDOWS-PREVIEW@0.2.8"

Then I can run the example, but I got this error then:
![image](https://cloud.githubusercontent.com/assets/1463415/6647703/761f1666-c98e-11e4-91ef-354d53f74ad2.png)

I still don't know to fix this issue.

**Comment by dr-dimitru** [comment]
Could you please make sure Neo4j is installed, running and available on: localhost:7474
Do you installed Neo4j and started it as described [here](https://github.com/VeliovGroup/Meteor-Leaderboard-Neo4j/blob/master/readme.md#neo4j)?

**Comment by snowcxt** [comment]
Yes, I installed Neo4j and it's running.
![image](https://cloud.githubusercontent.com/assets/1463415/6648344/e0ab796e-c995-11e4-87a1-15b87d5aff6a.png)

**Comment by dr-dimitru** [comment]
I'm on Neo4j 2.1.6 - running good, but on linux and mac
So, I think it's meteor's windows version issue

**Comment by snowcxt** [comment]
I guess so. But is it possible to fix this issue for the windows users?

**Comment by dr-dimitru** [comment]
Wait for stable release

**Comment by meduza** [comment]
@dr-dimitru Today i upgraded Neo4j to 2.2.0  and get the same issue:


    I20150326-09:32:23.996(3)? { [Error: [object Object]]
    I20150326-09:32:23.997(3)?   stack: [Getter/Setter],
    I20150326-09:32:23.997(3)?   message: { errors: [ [Object] ] },
    I20150326-09:32:23.997(3)?   __frame:
    I20150326-09:32:23.997(3)?    { name: 'GraphDatabase_prototype_query__20',
    I20150326-09:32:23.997(3)?      line: 710,
    I20150326-09:32:23.997(3)?      file: 'lib/GraphDatabase._coffee',
    I20150326-09:32:23.997(3)?      prev: undefined,
    I20150326-09:32:23.997(3)?      calls: 1,
    I20150326-09:32:23.997(3)?      active: false,
    I20150326-09:32:23.998(3)?      offset: 2,
    I20150326-09:32:23.998(3)?      col: 24 },
    I20150326-09:32:23.998(3)?   rawStack: [Getter] }
    I20150326-09:32:24.315(3)? Exception in callback of async function: Error: Meteor.N4JDB.query: [Meteor.neo4j.run]: Error: [object Object],791a843f33d05a058287de11f6c54a1d263e8cbeeb7f9ecbb17ebba1ceb10e0a,MATCH (u:User {_id: "ajWv4xmfoeQ4kAMwL"})-[:Friends]->(f) WHERE HAS (f._id) RETURN f._id AS ids,,Mon Mar 16 2015 11:20:01 GMT+0300 (MSK) [500]
    I20150326-09:32:24.315(3)?     at packages/ostrio:neo4jreactivity/ostrio:neo4jreactivity_driver.js:458:1
    I20150326-09:32:24.315(3)?     at packages/ostrio:neo4jreactivity/ostrio:neo4jreactivity_driver.js:12:1
    I20150326-09:32:24.315(3)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)


Neo4j 2.1.6 - running good.

**Comment by dr-dimitru** [comment]
Hi @snowcxt and @meduza 
I've released new updated and builded for windows version of [Driver](https://github.com/VeliovGroup/ostrio-neo4jdriver) and [Reactivity](https://github.com/VeliovGroup/ostrio-Neo4jreactivity), could you please check on your end if this release is fix issues you've met (sorry, I don't have enough time for testing)

**Comment by dr-dimitru** [comment]
@meduza I'll run tests on Neo4j v2.2.0 a bit later on this week.

**Comment by meduza** [comment]
@dr-dimitru I disabled default Neo4j-2.2.0 authentication and seems it works!

**Comment by dr-dimitru** [comment]
@meduza sound great! Could you please describe how you've disabled default auth or contribute it to the docs (readme.md) so this knowledge will be available to the community. Also are you on win or Mac?

**Comment by meduza** [comment]
@dr-dimitru To disable default authentication in Neo4j-2.2.0:
open file  /Your_Neo4j-2.2.0_install_path/conf/neo4j-server.properties
change line:  dbms.security.auth_enabled=true (to false)

**Comment by dr-dimitru** [comment]
@meduza thank you. Added to docs

**Comment by snowcxt** [comment]
still not working for me. I'm using windows 7 + meteor 1.1 + Neo4j-2.2.0 Community and changed the dbms.security.auth_enabled to false (BTW I changed the neo4j-server.properties file via the options UI) 
![image](https://cloud.githubusercontent.com/assets/1463415/6931016/7e38b1c6-d7bd-11e4-8020-92fbcd077398.png)

Here is what I get:
![image](https://cloud.githubusercontent.com/assets/1463415/6931045/ca0b1c6a-d7bd-11e4-95db-1095d385bf7d.png)

**Comment by meduza** [comment]
@snowcxt Check, can you connect to neo4j webadmin (http://localhost:7474) without authentication?

**Comment by snowcxt** [comment]
Sorry I'm a newbie of neo4j. Could you tell me how to connect to neo4j webadmin?

**Comment by dr-dimitru** [comment]
@snowcxt just go to http://localhost:7474 in your browser

**Comment by snowcxt** [comment]
Yes, I can

**Comment by dr-dimitru** [comment]
@snowcxt could you try to install everything by instructions and run [Meteor-Leaderboard-Neo4j](https://github.com/VeliovGroup/Meteor-Leaderboard-Neo4j) ?

**Comment by snowcxt** [comment]
I think I've installed everything. I just tried to install everything again but still got the same errors. BTW I'm using meteor 1.1 but your package is meteor 1.0.3.2. I have to run meteor update --release METEOR@1.1 to update the packages.

**Comment by dr-dimitru** [comment]
@snowcxt nope, [current package](https://github.com/VeliovGroup/ostrio-Neo4jreactivity/blob/master/package.js#L9) supports meteor 1.0 and above. Just run `meteor update` to update meteor and all packages to the latest versions

**Comment by snowcxt** [comment]
I'm using windows. meteor 1.0 doesn't support windows. Could you update the driver to support meteor 1.1?

**Comment by dr-dimitru** [comment]
@snowcxt current package supports meteor 1.0 and __above__

**Comment by snowcxt** [comment]
I can't run meteor update for windows. Could you update this example to 1.1?

![image](https://cloud.githubusercontent.com/assets/1463415/6969033/654384e8-d920-11e4-9b27-d89bada35738.png)

**Comment by dr-dimitru** [comment]
@snowcxt and @meduza I apologize, after digging into the troubleshooting on the Win platform there was incompatibility issue on MongoDB >= 2.6 with dotted keys, fixed in 69fcc535241f34f3e75b875388467f64041f8334
Guys, please update.

@snowcxt thank you, for your help

**Comment by snowcxt** [comment]
I got a new error when I ran the example:

Your app is crashing. Here's the latest log.

Started MongoDB.
Errors prevented startup:

While building the application:
node_modules/neo4j/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/has-ansi/cli.js:1:15: Unexpected token ILLEGAL
node_modules/neo4j/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/strip-ansi/cli.js:1:15: Unexpected token ILLEGAL
node_modules/neo4j/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/supports-color/cli.js:1:15: Unexpected token ILLEGAL
node_modules/neo4j/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/test/run.js:1:15: Unexpected token ILLEGAL
node_modules/neo4j/node_modules/request/node_modules/bl/test/sauce.js:1:15: Unexpected token ILLEGAL
node_modules\neo4j\node_modules\request\node_modules\node-uuid\test\test.html:1: bad formatting in HTML template

Your application has errors. Waiting for file change.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/1463415/6976325/f3c19908-d95c-11e4-8bb6-ebb731bdb315.png)

**Comment by dr-dimitru** [comment]
@snowcxt I'll try tomorrow day on the clean windows setup

**Comment by dr-dimitru** [comment]
@meduza could you please test new driver and neo4j-leaderboard example on your end?

**Comment by snowcxt** [comment]
I reinstalled the meteor and downloaded the lastest neo4j-leaderboard example

**Comment by dr-dimitru** [comment]
@snowcxt does neo4jreactivity driver runs in your project?

**Comment by snowcxt** [comment]
I used a different computer, updated meteor and download the example. It's working now. Thank you

**Comment by meduza** [comment]
@dr-dimitru I tested - it works!

    $meteor list
    http                    1.1.0  Make HTTP calls to remote servers
    meteor-platform         1.2.2  Include a standard set of Meteor packages in y...
    ostrio:neo4jdriver      0.2.11  Meteor.js node-neo4j wrapper to be used with ...
    ostrio:neo4jreactivity  0.6.0  Meteor.js Neo4j database reactivity layer

**Comment by dr-dimitru** [comment]
Guys, @meduza, @snoxcxt, thank you for your time

**Comment by meduza** [comment]
You are welcome! Thank you for the lib!

**Comment by snowcxt** [comment]
I tested again today. (win 8 + neo4j 2.2). It works.

**Comment by HunjaeJung** [comment]
That's what I want! Thanks..but we still need to fix the auth problem, right?

**Comment by dr-dimitru** [comment]
@HunjaeJung should be fixed after stable release of [node-neo4j v2](https://github.com/thingdom/node-neo4j/tree/v2)

**Comment by dr-dimitru** [comment]
Hello everyone,
Auth exception should be fixed in Neo4jDriver [v0.2.12](https://github.com/VeliovGroup/ostrio-neo4jdriver/commit/9b6fba3d54355701588fa304bf255093c862392c)
Please confirm on you end
