### ISSUE TITLE
Meteor 1.1 Windows Support

### ISSUE THREAD

**Issue by amg2nd** [VeliovGroup/ostrio-Neo4jreactivity#26]
> meteor update

=> Errors while initializing project:

While checking for ostrio:neo4jreactivity@0.4.3:
error: No compatible binary build found for this package. Contact the
package author and ask them to publish it for your platform.

**Comment by dr-dimitru** [comment]
@amg2nd You are using outdated version, use last one - [v0.5.4](https://github.com/VeliovGroup/ostrio-Neo4jreactivity/blob/master/package.js#L4)

**Comment by amg2nd** [comment]
I apologize ostrio:neo4jreactivity@=0.4.3 was set in my package list
