### ISSUE TITLE
HTTP Basic Auth Connection to Neo4j Server

### ISSUE THREAD

**Issue by AngelCabo** [VeliovGroup/ostrio-Neo4jreactivity#35]
Is it possible to establish a remote server connection that requires http basic authentication? After poking around the library it looks like the initial connect would have to change from something like this:
```javascript
var httpRes = HTTP.call('GET', this.url);
```
to this:
```javascript
var httpRes = HTTP.call('GET', this.url, {
    auth: this.user + ':' + this.pass
});
```

At the moment, I get a 401 if I try to do something like `NEO4J_URL="http://user:pass@server.com" meteor`.

**Comment by dr-dimitru** [comment]
@AngelCabo please post here your console output. What kind of error it returns to you?
Please make sure you've read docs of [Neo4jDriver](https://github.com/VeliovGroup/ostrio-neo4jdriver)
Also try to setup `connectionURL `:
```javascript
Meteor.neo4j. connectionURL = 'http://user:pass@server.com';
```

**Comment by AngelCabo** [comment]
with `Meteor.neo4j.connectionURL = 'http://user:pass@server.com';`
I get a 401 error:
![screenshot](https://cloud.githubusercontent.com/assets/478246/7339859/e5f9e978-ec4a-11e4-9521-f5da51d17f2b.png)

When I call a custom "makeConnection" server side Meteor method I wrote to use the Http package directly with basic auth, I get a 200:
```
Meteor.methods({
  'makeConnection': function () {
    var HTTP = Meteor.wrapAsync(Package.http.HTTP.call);
    var httpRes = HTTP('GET', "http://server.com", {
      auth: 'user:pass'
    });
    return httpRes.statusCode;
  },
```
I probably should have opened the issue on the neo4jdriver project.

**Comment by dr-dimitru** [comment]
@AngelCabo thank you for issue.
Auth exception should be fixed in Neo4jDriver [v0.2.12](https://github.com/VeliovGroup/ostrio-neo4jdriver/commit/9b6fba3d54355701588fa304bf255093c862392c)
Please confirm on you end

**Comment by AngelCabo** [comment]
Thanks for the fast fix! Working on my side.

**Comment by dr-dimitru** [comment]
@AngelCabo thanks for issue and testing on your end
