### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by ccorcos** [VeliovGroup/ostrio-Neo4jreactivity#39]
I've read through Neo4j and read through the documentation here and I'm pretty confused how all this works.

I'm a little confused about how Mongo is involved in this -- what does link do here: `Meteor.neo4j.subscribe(name, [opts], [link])`?

Is there a minimongo version of Neo4j running on the client? It appears that there isn't...

My understanding is that without insecurely allowing the client to run server-side queries, publications are the only way of querying Neo4j data. Thus, we can subscribe to a query which will reactively update the results on the client. Then we can create a cursor by using a query on that subscription. This query is a reactive cursor.

Now neo4j methods are just like Meteor methods except the options are turned into query params... this seems a bit insecure, but ok...

I guess, I just generally feel like the api here is too complicated. There are 3 different globals exposed to Meteor that all look like they have to do with neo4j. Subscriptions and queries appear to be pretty much the same thing on the client. Neo4j methods appear to be a wrapper for Meteor methods and theres just much more to this API that I don't understand the need for. Then there are things like collections which are confusing to me because there appears to be only one database...

Can you clarify some of this for me? Whats the state of this package? Is it used at all in production? What else needs to be done?

**Comment by ccorcos** [comment]
Any ideas how to do this reactivity without piggy-backing on Mongo?

**Comment by dr-dimitru** [comment]
What is wrong to base on top of Mongo?

By the way I'm already discussed about it with many people. Answer is - No.

**Comment by ccorcos** [comment]
Apart from an unnecessary dependency, the biggest problem I see with using Mongo is scaling. You're using mongo to cache results and sync them to the client. There may be many different ways of querying to the same bits of data. For example, if you are looking for a bunch of posts based on the people you follow, then surely there are many different ways of a post ending up in your feed. However, by caching them with mongo, that post is going to end up in the database many times for everyone's personalized feed. The size of the Mongo database will exponentially grow with respect to the size of the Neo4j database...

I'm also unsure how to observe changes to the database. Suppose we do a shortest path query or something like that, then we remove an edge from the graph -- how do we know if our shortest path result was effected by this edge?

**Comment by dr-dimitru** [comment]
@ccorcos Answering on your first question:
There is two different ways to use Neo4j in neo4jReactivity:
 - Via `call` and `methods`
 - Via `collection`, `publish` and `subscribe`

You can use them both aside to each other, cause `publish` and `subscribe` way doesn't offer `update`, `insert` and `remove` functionality on collection. The `publish` and `subscribe` works only one way - reactively update data, which updated on server-side.
The `collection` created via `Meteor.neo4j.collection()` method generally represents local mini-mongo set. 

`Meteor.neo4j.subscribe(name, [opts], [link])` - `link` here binds collection set to node link in results returned from Neo4j, please see [subscribe](https://github.com/VeliovGroup/Meteor-Leaderboard-Neo4j/blob/master/leaderboard.js#L15) and [query](https://github.com/VeliovGroup/Meteor-Leaderboard-Neo4j/blob/master/leaderboard.js#L77) form Leaderboard example. This method allows reactively `find()` and `fetch()` returned data from Neo4j.

Also you allowed to run `Meteor.neo4j.query()` method on client or server side, on whole Neo4j database.

Cache collection won't be overgrown - cause it's limited to number of same queries in your application. I won't say it wouldn't be big - cause for example if you query current user's node from Neo4j - Neo4jCacheCollection will store every result for every user.

But you're free to create your own reactivity layer, or listen for something you depend on - within `N4JDB.listen()` method of [Meteor's Neo4jDriver](https://github.com/VeliovGroup/ostrio-neo4jdriver/blob/master/ostrio:neo4jdriver.js#L108)

Yes, this package used at our internal application (production stage).

**Comment by ccorcos** [comment]
> Cache collection won't be overgrown - cause it's limited to number of same queries in your application. I won't say it wouldn't be big - cause for example if you query current user's node from Neo4j - Neo4jCacheCollection will store every result for every user.

What if I have a query like this `MATCH (user {name:'joe'}) -[:FOLLOWS]->()-[:STARRED]->(post) RETURN post SORT post.date LIMIT 20`. Then these results will be caches for every user. Right?

**Comment by dr-dimitru** [comment]
@ccorcos yes, one cache record for every user with property `name` equals `joe`

**Comment by ccorcos** [comment]
Ok. Thats just not going to scale for me... bummer.
