### ISSUE TITLE
Meteor.neo4j.query keeps returning the same result 

### ISSUE THREAD

**Issue by BenjaminHolland10** [VeliovGroup/ostrio-Neo4jreactivity#49]
I'm writing a query that matches a node with two properties except when I call the query it returns the same result multiple times. I know I'm passing in different id's and it actually returns different results if I change the Match variable( the a in (a:User)) but I don't know why its not returning the correct results all the time. I've tested the query in the console and it works.Here's my function and the results.
 
![screen shot 2015-06-25 at 6 44 45 pm](https://cloud.githubusercontent.com/assets/10546097/8367241/4783a46a-1b6a-11e5-9aff-a0264590db05.png)

![screen shot 2015-06-25 at 6 42 58 pm](https://cloud.githubusercontent.com/assets/10546097/8367200/07fd7d7a-1b6a-11e5-81b1-aeb75e8963b0.png)

**Comment by BenjaminHolland10** [comment]
As you can see the user input variable is different.

**Comment by dr-dimitru** [comment]
@BenjaminHolland10 Hi, do you ever tried to query like this:
```sql
MATCH (b:User {id: {id}, registered: {registered}}) RETURN b
```
Could you please try the query I'm suggested above, and let me know about results.

**Comment by BenjaminHolland10** [comment]
Yeah that was my first attempt at it. I just tried it again just to make sure and the problem persisted. 
![screen shot 2015-06-25 at 7 01 19 pm](https://cloud.githubusercontent.com/assets/10546097/8367498/bcae34d8-1b6c-11e5-8ff5-34cb2ea7148c.png)
![screen shot 2015-06-25 at 7 01 36 pm](https://cloud.githubusercontent.com/assets/10546097/8367499/bcc04cc2-1b6c-11e5-8327-ffdd6d95bcbd.png)

**Comment by BenjaminHolland10** [comment]
This is the function that calls it just for reference. Don't think it has an effect. 
![screen shot 2015-06-25 at 7 06 21 pm](https://cloud.githubusercontent.com/assets/10546097/8367549/51fde5a6-1b6d-11e5-86e0-e365d0b7374e.png)

**Comment by dr-dimitru** [comment]
Just to confirm, please do:
 1. `console.log(error, data);`
 2. Run same code on both `server` and `client`, with same `log` as above
 3. On `server` try to run query inside: `Meteor.N4JDB.query(...);`

**Comment by BenjaminHolland10** [comment]
First two are registered last one is not. 

![screen shot 2015-06-25 at 7 20 00 pm](https://cloud.githubusercontent.com/assets/10546097/8367718/36ab42ec-1b6f-11e5-8a31-1b15480524f7.png)

**Comment by dr-dimitru** [comment]
@BenjaminHolland10 inside of `Meteor.N4JDB.query(...);` run `console.log(error, data);` without `b` property. 
And what about `client` side? Same result?

**Comment by BenjaminHolland10** [comment]
Client 
![screen shot 2015-06-25 at 7 34 40 pm](https://cloud.githubusercontent.com/assets/10546097/8367874/4d9dc996-1b71-11e5-8e1e-85b7225f571e.png)
code: (N4JDB was giving me a undefined method error)
![screen shot 2015-06-25 at 7 35 55 pm](https://cloud.githubusercontent.com/assets/10546097/8367884/817f16ac-1b71-11e5-97f8-7f07629fb8fb.png)

Server 
![screen shot 2015-06-25 at 7 25 58 pm](https://cloud.githubusercontent.com/assets/10546097/8367877/585833da-1b71-11e5-86e5-3c87c2017898.png)
code:
![screen shot 2015-06-25 at 7 26 12 pm](https://cloud.githubusercontent.com/assets/10546097/8367888/936e9928-1b71-11e5-85ba-3a4ce869d62e.png)

**Comment by BenjaminHolland10** [comment]
N4JDB will work in my case just thought i'd let you know and document it for any other user facing the problem.

**Comment by BenjaminHolland10** [comment]
What would be the best way to access the data returned by the N4JDB query? @dr-dimitru

**Comment by dr-dimitru** [comment]
Same as in `Meteor.neo4j.query()`, last argument is callback with `error` and `data`. In `data` you should have raw data from Neo4j.

**Comment by BenjaminHolland10** [comment]
I'm sorry I'm pretty new to Javascript but when I try return the data from the callback it the return value is undefined. This probably has something to do with scope but I'm not sure. Here's what I have right now. 
![screen shot 2015-06-25 at 8 36 24 pm](https://cloud.githubusercontent.com/assets/10546097/8368552/de54d030-1b79-11e5-8544-9f7c599874dd.png)

**Comment by dr-dimitru** [comment]
@BenjaminHolland10 you're fine.
I'm sure there is no `data[0]`, so just `console.log(data);`, then construct your logic statement based on what returned from database in different cases.

**Comment by BenjaminHolland10** [comment]
It's not parsing the data I'm having trouble with It's actually getting the data out of the callback into the outer function. Thank you so much for responding.

**Comment by dr-dimitru** [comment]
Yes, `Meteor.N4JDB` works directly with Neo4j DB and returns data as it is presented in Neo4j.
Then `Meteor.neo4j` parce and presents data in Mongo-like way used basically in Meteor

**Comment by BenjaminHolland10** [comment]
http://stackoverflow.com/questions/28945481/javascript-callback-returns-undefined-using-neo4j-and-meteor
This is my question

**Comment by dr-dimitru** [comment]
Okay, I see the right answer, if you prefer to work with data on server side.
I believe in your case better to work with Neo4j [as collection and publish/subscribe](https://github.com/VeliovGroup/ostrio-Neo4jreactivity/#as-collection-and-publishsubscribe) way. 
See [this example](https://github.com/VeliovGroup/Meteor-Leaderboard-Neo4j/blob/master/leaderboard.js#L10).

**Comment by BenjaminHolland10** [comment]
Thanks for the advice. I have to rewrite a lot of my app but working the publish/subscribe way it a lot cleaner and easier to write.
