### ISSUE TITLE
Really have a problem the values don't back

### ISSUE THREAD

**Issue by camilamacedo86** [VeliovGroup/ostrio-Neo4jreactivity#56]
getShortDirections: function(origem,destination){

        var match = 'MATCH (from:Location { name:"'+origem+'" }), (to:Location { name: "'+destination+'"}) , path = (from)-[:CONNECTED_TO*]->(to) ';
        var ret = ' RETURN path AS shortestPath, ';
        var reduce = '  reduce(distance = 0, r in relationships(path) | distance+r.distance) AS totalDistance ';
        var order = '  ORDER BY totalDistance ASC  LIMIT 1 ';
        var query = match + " " + ret + " "+ reduce +" "+ order;

        var shortestPath;
        var totalDistance;
        Meteor.N4JDB.query(query, null, function(err, data){

            console.log( data.shortestPath );
            console.log( data.totalDistance );
            shortestPath = data.shortestPath;
            totalDistance = data.totalDistance;
        });

        return shortestPath;
    },

The database consult :+1: 

<img width="1398" alt="screen shot 2015-08-23 at 5 47 02 pm" src="https://cloud.githubusercontent.com/assets/7708031/9430121/f3cf6498-49be-11e5-98f2-cb9d70881d36.png">

Result in meteor application :+1: 

=> Meteor server restarted
I20150823-17:44:45.402(-3)? undefined
I20150823-17:44:45.403(-3)? undefined

**Comment by camilamacedo86** [comment]
@dr-dimitru please can you help me ? Don't came back the values. I can show for you . My skype is camilamacedogigin

**Comment by dr-dimitru** [comment]
Could you please `console.log()` both `error` and `data`? And a full `query` variable and copy/paste it to Neo4j console to make sure your query composed in right way

**Comment by camilamacedo86** [comment]
@dr-dimitru the query are good. But the problem is when pass in the return don't came back yet after this came back the result . If you can call me in the skype I can show for you

**Comment by dr-dimitru** [comment]
It is async function, use Fibers: [tutorial](http://themeteorchef.com/snippets/synchronous-methods/)

**Comment by dr-dimitru** [comment]
@camilamacedo86 Solved?

**Comment by dr-dimitru** [comment]
@camilamacedo86 issue will be closed in a week due to no response from topic starter

**Comment by dr-dimitru** [comment]
closed due to no response from topic starter
