### ISSUE TITLE
First call to Meteor.neo4j.query("...") returns null

### ISSUE THREAD

**Issue by blackslate** [VeliovGroup/ostrio-Neo4jreactivity#58]
Version 0.91
Steps to reproduce:
- I have an Neo4j database that is populated with a number of nodes and relationships
- I create a bare-bones Meteor application, with all the dependencies for Neo4j.
- I add a JS file in the lib folder, with the script:
  
  Meteor.neo4j.allowClientQuery = true;
  Meteor.neo4j.connectionURL = 'http://neo4j:1234@localhost:7474';
  Meteor.neo4j.set.deny(Meteor.neo4j.rules.write);
- I launch the Meteor app
- In a browser window, I open the Developer Tools console, and type:
  
  Meteor.neo4j.query('MATCH (n) RETURN n').get()
- The output is:
  null
- I run my query a second time:
  
  Meteor.neo4j.query('MATCH (n) RETURN n').get()
- This time, the call returns a result:
  
  Object {n: Array[235]}

**Comment by dr-dimitru** [comment]
This is correct behaviour you need to wrap this into `Tracker.autorun()` or use as Template helper
