### ISSUE TITLE
publish/subscribe multiple nodes

### ISSUE THREAD

**Issue by schabluk** [VeliovGroup/ostrio-Neo4jreactivity#60]
From usage examples:

``` javascript
friends = Meteor.neo4j.collection 'friends'
friends.publish 'allFriends', () ->
  return "MATCH (user {_id: {userId}})-[:FriendOf]->(friends) RETURN friends"
friends.subscribe 'allFriends', {userId: Meteor.userId()}, 'friends'
```

The link parameter in subscribe method is a single node. How can I get multiple nodes from subscription, when my publish funtion returns more than one node?

``` javascript
friends.publish 'allFriends', () ->
  return "MATCH (user {_id: {userId}})-[:FriendOf]->(friends) RETURN user, friends"
```

**Comment by dr-dimitru** [comment]
Hi @schabluk 
Currently only creating multiple subscriptions for each object.

But major driver release is coming soon (1-2 days), there is this issue will be solved.

**Comment by schabluk** [comment]
Great, thank you!
