### ISSUE TITLE
Return multiple nodes in a subscribe?

### ISSUE THREAD

**Issue by davidworkman9** [VeliovGroup/ostrio-Neo4jreactivity#65]
I can run something like this in a Meteor method and get back what I expect:

```
MATCH (node)-[r]->(node2) RETURN node2, node, r
```

but if I run the same thing in a publish I can only select either node, node2 or r.

**Comment by dr-dimitru** [comment]
Right, it is expected behaviour.
Btw you might be interested to use full-featured (but non-reactive) [neo4j driver](https://github.com/VeliovGroup/ostrio-neo4jdriver)
