### ISSUE TITLE
es6 multiline string query error

### ISSUE THREAD

**Issue by akaiworld** [VeliovGroup/ostrio-Neo4jreactivity#66]
I am new to using es6 features. But this seems to be a strange behaviour.

When i use multiline query: 

``` js
return `
   MATCH (node:Dialog) 
   RETURN node
`;
```

I do not get results, like when i do like this: 

> return 'MATCH (node:Dialog) RETURN node';

**Comment by dr-dimitru** [comment]
idk about ES6 (_don't have a chance to test it with this lib_), but I guess on compilation with Babel it adds a caret (_new line_) at the EOL, which is not supported in Cypher.

**Comment by dr-dimitru** [comment]
Btw now it's better to use [neo4jdriver](https://github.com/VeliovGroup/ostrio-neo4jdriver) package, it's has more features, and well-tested, and will be updated soon.

This package will be updated later, and currently has lots of lacks.

**Comment by akaiworld** [comment]
I would like to use  neo4jdriver package, but it is not reactive. Do i understand it right?

**Comment by dr-dimitru** [comment]
Yes, it is not reactive _on the client_. But [neo4jdriver](https://github.com/VeliovGroup/ostrio-neo4jdriver) can be reactive on the server 

To make [neo4jdriver](https://github.com/VeliovGroup/ostrio-neo4jdriver) reactive on the client check out [meteor-any-db](https://github.com/ccorcos/meteor-any-db) package

And API of this package might change a lot in new version.

**Comment by akaiworld** [comment]
Nice, i will check this, thanks!
Is the one with -fibers postfix also server-reactive? On my machine the one with -fibers postfix worked, not the original one.

**Comment by dr-dimitru** [comment]
`-fibers` and _fiberless_ versions has same codebase, just different NPM dependencies.

BTW with Meteor > 1.3, you can use NPM package directly (see [neo4j-fiber](https://github.com/VeliovGroup/neo4j-fiber)):

``` shell
meteor npm install neo4j-fiber
```

And require it as a module:

```
Neo4jDB = require('neo4j-fiber');
```

**Comment by akaiworld** [comment]
BTW in neo4j-fiber multiline queries work fine.

**Comment by dr-dimitru** [comment]
Yes, in neo4j-fiber queries goes thru _clean up_, to make sure it's valid

**Comment by dr-dimitru** [comment]
@akaiworld thank you for testing with ES6

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

//cc @mksh-su
