### ISSUE TITLE
Access to database is not hidden on the client

### ISSUE THREAD

**Issue by akaiworld** [VeliovGroup/ostrio-Neo4jreactivity#67]
When i open my app in the browser i can easilly find the link with login & password to my graphene database in files on the client. 

So anyone can get access to my DB! How to hide my 
Meteor.neo4j.connectionURL = '...';
line from clients?

**Comment by dr-dimitru** [comment]
Wrap it into `if (Meteor.isServer) { /* set connectionURL here */ };`

**Comment by akaiworld** [comment]
Ok, the problem was that i left the same string commented on the client. When removed, the line disappeared on the clients files.
