### ISSUE TITLE
No results without Meteor.neo4j.allowClientQuery 

### ISSUE THREAD

**Issue by akaiworld** [VeliovGroup/ostrio-Neo4jreactivity#68]
When i do not use 
Meteor.neo4j.allowClientQuery = true;
I do not get results at all. When i do use. Everything works. But i do not need clients to be able to execute queries. How to manage this?

**Comment by dr-dimitru** [comment]
To allow only read queries on client use:

``` js
Meteor.neo4j.set.deny(neo4j.rules.write);
```

**Comment by dr-dimitru** [comment]
Btw read docs in this package: https://github.com/VeliovGroup/Meteor-Leaderboard-Neo4j

**Comment by akaiworld** [comment]
Thats the point that I do not want to make clients able to make ANY query they wnat. Only via methods, where i can make special checks. Otherwise they will be able to read any information, even that which they should not.

**Comment by dr-dimitru** [comment]
I didn't get you, you don't have results on server?

**Comment by akaiworld** [comment]
``` js
Meteor.neo4j.call('allNodes', {}, (error, data) => {
    console.log(error); console.log(data);
});
```

Without Meteor.neo4j.allowClientQuery = true;
returned undefined, nothing on the console at all.

With Meteor.neo4j.allowClientQuery = true; 
returned undefined, error - null, data - NEEDED DATA

**Comment by dr-dimitru** [comment]
Post your method code, please

**Comment by akaiworld** [comment]
Here is the methods code: 

``` js
Meteor.neo4j.methods({
    allNodes: function(){
        log('Server allNodes')
        return 'MATCH (node:Dialog) RETURN node';
    }, 
    addDialog: function(){
        log('Server addDialog')
        return 'CREATE (:Dialog {id: {id}});';
    }
});
```

**Comment by dr-dimitru** [comment]
`Meteor.neo4j.allowClientQuery` needs to be set to `true` to call Methods, see: [here](https://github.com/VeliovGroup/ostrio-Neo4jreactivity/blob/master/methods.coffee#L9) and [here](https://github.com/VeliovGroup/ostrio-Neo4jreactivity/blob/master/driver.coffee#L503)

**Comment by akaiworld** [comment]
So on production there only one way - to give clients possibility to make any read calls?

**Comment by dr-dimitru** [comment]
You can deny all commands via:

``` js
Meteor.neo4j.set.deny('*');
```

**Comment by akaiworld** [comment]
Nice! Now it works as expected! Thank you very much!
