### ISSUE TITLE
can i subscribe this publish method in Ionic Framework

### ISSUE THREAD

**Issue by vishalwayachal** [VeliovGroup/ostrio-Neo4jreactivity#69]
Hello,

If i publish method in Meteor and using astriod js to subscribed in Ionic framework is this possible 
Can you please suggest a solution for this.

**Comment by dr-dimitru** [comment]
Hi @vishalwayachal 
I've never faced astriod. Do you have an issue right now?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
