### ISSUE TITLE
No response in simple application

### ISSUE THREAD

**Issue by C0mmander198** [VeliovGroup/ostrio-Neo4jreactivity#70]
I'm trying to get a simple example up and running.

I'm using a config file in my lib folder with these lines

```
  Meteor.neo4j;
  Meteor.neo4j.connectionURL = 'http://neo4j:neo4j@localhost:7474';
```

and in the server main file I'm running

```
Meteor.startup(() => {
  allUsers = Meteor.neo4j.query('MATCH (users:User) RETURN users');
  var users = allUsers.get().users;
});
```

I'm able to connect to the neo4j instance in the browser interface or by using Postman without any issues.
However when I execute the above app I get the following notification:

> Meteor is successfully connected to Neo4j on http://neo4j:neo4j@localhost:7474  

and right afterwards

> TypeError: Cannot read property 'users' of undefined 

indicating that the allUsers object is not available. When trying to use the callback approach it is never entering the callback function.

Am I missing something? Maybe some call before I execute the query in the startup function of the server?

**Comment by dr-dimitru** [comment]
@C0mmander198 is it solved?

**Comment by C0mmander198** [comment]
Yes. I went to lunch, came back and it worked without any code change...Not sure - maybe some issue with the neo4j instance

**Comment by dr-dimitru** [comment]
Lunch helps much )
