### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by vraptor75011** [VeliovGroup/ostrio-Neo4jreactivity#8]
Hi

I've been trying to use your package and keep getting various errors.
Could you please provide an example app ?

Tks

**Comment by lifeinchords** [comment]
+1.. very interested in experimenting with Meteor + neo

**Comment by dr-dimitru** [comment]
Good news everyone ( @vraptor75011 , @lifeinchords )!
`--example leaderboard` app on top of Neo4j now available [here (Meteor Leaderboard Neo4j)](https://github.com/VeliovGroup/Meteor-Leaderboard-Neo4j)

By the way both driver and reactivity layer was improved and updated

**Comment by dr-dimitru** [comment]
Hi guys @vraptor75011 , @lifeinchords 
Please let me know how example app works on your end

**Comment by lifeinchords** [comment]
Thanks, gonna try it now!



      ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

         Steven J. Dale   @lifeinchords <https://twitter.com/lifeinchords>
 @makeparallels <http://www.twitter.com/makeparallels>

      ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

**Comment by vraptor75011** [comment]
Tks, Will try today
